### ISSUE TITLE
FluentValidationPipelineBehavior issues

### ISSUE THREAD

**Issue by BlackWolves-nl** [AdaskoTheBeAsT/AdaskoTheBeAsT.FluentValidation.MediatR#2]
Getting following errors when query/command is send:
SimpleInjector.ActivationException: The constructor of type FluentValidationPipelineBehavior<GetApiMethodsQuery, IEnumerable<ApiMethodDTO>> contains the parameter with name 'validators' and type IEnumerable<IValidator<GetApiMethodsQuery>>, but IEnumerable<IValidator<GetApiMethodsQuery>> is not registered. For IEnumerable<IValidator<GetApiMethodsQuery>> to be resolved, it must be registered in the container. There is, however, a registration for IValidator<GetApiMethodsQuery>; Did you mean to depend on IValidator<GetApiMethodsQuery>?

As far as i know there are no IEnumerable<IValidator<TRequest>> in the container. Or do you need to register validators in a specific way other then in your other project:
_container.AddFluentValidation(cfg => {
                cfg.WithAssembliesToScan(_assembliesToScan_validators);
            });

If i make a new pipeline SingleFluentValidationPipelineBehavior and make it expect a single IValidator all is working fine.
Is that the way to go? Or am i doing something wrong

**Comment by AdaskoTheBeAsT** [comment]
hi @BlackWolves-nl - confirmed - it is an issue - I will fix it

**Comment by AdaskoTheBeAsT** [comment]
hi @BlackWolves-nl - it was fixed - please look at readme - now there is two way of registering validator - single per target or collection per target - then proper validation pipeline needs to be used - please take latest nuget packages - this one should be in nuget in 1h
